name: local-services

services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - local-services
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  local-services:
    external: true

volumes:
  postgres_data:
